### ISSUE TITLE
Feature: Add support for `hub_routing_preference` property on `azurerm_virtual_hub` resource

### ISSUE THREAD

**Issue by jinkang23** [Azure/terraform-azurerm-avm-ptn-virtualwan#28] opened 2024-02-08 23:52 UTC
Latest version `0.3.0` of `avm-ptn-virtualwan` module doesn't appear to expose an input variable to specify the `hub_routing_preference` argument to set the routing preference to `ASPath` or `VpnGateway` on `azurerm_virtual_hub` resource. 

This is similar to the issue reported in the  `caf-enterprise-scale` module: [https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/861](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/861).  

I have considered working around this by using `azapi_update_resource` but I can't set `ignore_changes` on modules. 

Any plans to add support for this in the next release? 

Thank you!

**Comment by khushal08** [comment] 2024-02-09 03:30
Thanks @jinkang23 for the feedback. We will look at your request.

**Comment by philipstreet** [comment] 2024-04-23 14:32
Isn't this a duplicate of https://github.com/Azure/terraform-azurerm-avm-ptn-virtualwan/issues/7?

**Comment by khushal08** [comment] 2024-05-07 06:13
Fix pushed in 0.v.4.2

**Closed by khushal08** 2024-05-07 06:13 UTC
Labels: enhancement
